"use client";

import { useFormState, useFormStatus } from "react-dom";
import { useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { generateTemplate } from "./actions";
import { Bot, Loader2 } from "lucide-react";
import {
  useUser,
  useFirestore,
  errorEmitter,
  FirestorePermissionError,
} from "@/firebase";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending}>
      {pending ? (
        <>
          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          Generating...
        </>
      ) : (
        "Generate Template"
      )}
    </Button>
  );
}

export default function TemplatesPage() {
  const { toast } = useToast();
  const { user } = useUser();
  const firestore = useFirestore();
  const initialState = { success: false, message: "", template: "", prompt: "" };
  const [state, formAction] = useFormState(generateTemplate, initialState);
  const savedPromptRef = useRef<string | undefined>();

  useEffect(() => {
    if (
      state.success &&
      state.template &&
      state.prompt &&
      state.prompt !== savedPromptRef.current &&
      user &&
      firestore
    ) {
      savedPromptRef.current = state.prompt;

      const templatesCollection = collection(
        firestore,
        `users/${user.uid}/templates`
      );
      const templateData = {
        userId: user.uid,
        prompt: state.prompt,
        content: state.template,
        createdAt: serverTimestamp(),
      };

      addDoc(templatesCollection, templateData)
        .then(() => {
          toast({
            title: "Template Saved",
            description: "Your new template has been saved to your collection.",
          });
        })
        .catch((e) => {
          savedPromptRef.current = undefined; // Allow retry on failure
          const permissionError = new FirestorePermissionError({
            path: templatesCollection.path,
            operation: "create",
            requestResourceData: templateData,
          });
          errorEmitter.emit("permission-error", permissionError);
          toast({
            variant: "destructive",
            title: "Error Saving Template",
            description:
              "Could not save the generated template. You may not have permissions.",
          });
        });
    }

    if (!state.success && state.message) {
      // Only show toast if the message is new for this submission
      if (state.prompt && state.prompt !== savedPromptRef.current) {
        toast({
          variant: "destructive",
          title: "Error",
          description: state.message,
        });
      }
    }
  }, [state, user, firestore, toast]);

  return (
    <div className="grid gap-6">
      <Card>
        <form action={formAction}>
          <CardHeader>
            <CardTitle>AI Template Generator</CardTitle>
            <CardDescription>
              Describe the template you want to create. The generated template will be automatically saved to your collection.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-2">
              <Label htmlFor="prompt">Your Prompt</Label>
              <Textarea
                id="prompt"
                name="prompt"
                placeholder="e.g., A professional invoice template for a freelance web developer..."
                className="min-h-24"
                required
              />
            </div>
          </CardContent>
          <CardFooter>
            <SubmitButton />
          </CardFooter>
        </form>
      </Card>
      {state.template && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Bot className="w-6 h-6" />
              Generated Template
            </CardTitle>
            <CardDescription>
              Here is the template generated by the AI. You can copy and paste it.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <pre className="bg-secondary p-4 rounded-md text-sm overflow-x-auto">
              <code>{state.template}</code>
            </pre>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
